PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZTOCORRENCIAS-OCORRENCIA_ID .
    FIELD ZTOCORRENCIAS-ENTREGA_ID .
    FIELD ZTOCORRENCIAS-DATA_OCORRENCIA .
    FIELD ZTOCORRENCIAS-DESCRICAO .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZTOCORRENCIAS-OCORRENCIA_ID .
  module detail_pai.
 endchain.
