PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZTMOTORISTAS-MOTORISTA_ID .
    FIELD ZTMOTORISTAS-NOME .
    FIELD ZTMOTORISTAS-CPF .
    FIELD ZTMOTORISTAS-CNH .
    FIELD ZTMOTORISTAS-VALIDADE_CNH .
    FIELD ZTMOTORISTAS-STATUS .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZTMOTORISTAS-MOTORISTA_ID .
  module detail_pai.
 endchain.
